// Renders a compiled ACTION into text output: per-core pseudo-assembly
// listings and a C memory-map header. This is a source-generation step
// only — it does not invoke an actual assembler/linker. The .gen.s files
// use the mnemonics as written in the spec (a mix of Cortex-M0+ Thumb
// instructions and unresolved pseudo-ops like "LOAD ... into r1,r2,r7"),
// so treat them as a documented intermediate form, not final ARM asm ready
// to hand to `arm-none-eabi-as`.

export function generateAsm(compiled, coreKey) {
  const lines = [
    `@ Auto-generated by sovereign-gate compiler — do not edit by hand.`,
    `@ ACTION: ${compiled.action}   CORE: ${coreKey}`,
    ''
  ];

  for (const block of compiled.cores[coreKey]) {
    lines.push(`@ -- ${block.primitive} --`);
    for (const instr of block.instructions) lines.push(`    ${instr}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function generateMemoryMapHeader(ast) {
  const lines = ['#pragma once', '', '// Auto-generated from the MONOLITH.DELTA spec — do not edit by hand.', ''];

  for (const [name, bank] of Object.entries(ast.memoryBanks)) {
    lines.push(`#define ${name}_ORIGIN ${toHex(bank.ORIGIN)}`);
    lines.push(`#define ${name}_SIZE   ${bank.SIZE}u`);
  }
  lines.push('');

  for (const [name, frame] of Object.entries(ast.frames)) {
    lines.push(`typedef struct __attribute__((aligned(${frame.align}))) {`);
    for (const field of frame.fields) {
      lines.push(`  uint32_t ${field.name}${field.count > 1 ? `[${field.count}]` : ''};`);
    }
    lines.push(`} frame_${name.toLowerCase()}_t;`);
    lines.push('');
  }

  return lines.join('\n');
}

function toHex(n) {
  return `0x${Number(n).toString(16).toUpperCase().padStart(8, '0')}`;
}
